### ISSUE TITLE
margin 0 auto是什么选择器？

### ISSUE THREAD

**Issue by cooper1x** [leaf-hsiao/catfish#10]
css的第53行
而且全文整体有些偏下，不知道你设置的哪里的margin-top

**Comment by leaf-hsiao** [comment]
请补充一下详细说明

**Comment by cooper1x** [comment]
[catfish/catfish.css at master · leaf-hsiao/catfish](https://github.com/leaf-hsiao/catfish/blob/master/catfish.css)

```CSS
margin 0 auto {
  padding: 20px 30px 50px;
}
```
这个地方很奇怪
